# Generated by Django 4.1.7 on 2023-10-30 15:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_mobile', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'الزبائن',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('relative_phone_number', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': ' الموظفون',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255, verbose_name='detail')),
                ('category', models.CharField(default='Test', max_length=30)),
                ('price', models.FloatField(default=1)),
                ('price_list', models.CharField(choices=[('مفرد', 'مفرد'), ('جملة', 'جملة'), ('شراء', 'شراء'), ('قسط', 'قسط')], default='مفرد', max_length=30)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('IQD', 'IQD'), ('$', 'Dollar')], default='IQD', max_length=30)),
            ],
            options={
                'verbose_name_plural': ' المصاريف',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=8, unique=True)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': ' فاتورة الشراء',
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=8, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('مدفوع', 'مدفوع'), ('غير مدفوع', 'غير مدفوع'), ('المردود', 'المردود')], default='مدفوع', max_length=10)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'verbose_name_plural': 'فاتورة البيع',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': ' الموردين',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'المستودعات',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('total_amt', models.FloatField(default=0, editable=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('sub_total', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='percentage', editable=False, max_length=30)),
                ('discount_value', models.FloatField(blank=True, null=True, verbose_name='Discount Percentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saleinvoice')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'verbose_name_plural': ' بند المبيعات',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fines', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('slfa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'verbose_name_plural': ' الرواتب',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('total_amt', models.FloatField(default=0, editable=False)),
                ('pur_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchase')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'verbose_name_plural': ' العنصر الذي تم شراؤه',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
        migrations.CreateModel(
            name='Payment_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('q_type', models.CharField(choices=[('نقد', 'نقد'), ('قستی ١', 'قستی ١'), ('قستی ٢', 'قستی ٢'), ('قستی ٣ ', ' قستی ٣'), ('قستی ٤', 'قستی ٤'), ('قستی ٥', 'قستی ٥'), ('قستی ٦ ', ' قستی ٦'), ('قستی ٧', 'قستی ٧'), ('قستی ٨', 'قستی ٨'), ('قستی ٩ ', ' قستی ٩'), ('قستی ١٠', 'قستی ١٠'), ('قستی ١١', 'قستی ١١'), ('قستی ١٢ ', ' قستی ١٢')], max_length=10, verbose_name='Payment type')),
                ('paid_amount', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_date', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=100)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saleinvoice')),
            ],
            options={
                'verbose_name_plural': 'إدخال الدفع',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.FloatField(default=0, null=True)),
                ('sale_qty', models.FloatField(default=0, null=True)),
                ('total_bal_qty', models.FloatField(default=0)),
                ('return_qty', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('purchase', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.purchase')),
                ('sale', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.saleinvoice')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'verbose_name_plural': ' تفاصيل المخزون',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Sick', 'Sick')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'verbose_name_plural': ' الغيابات',
            },
        ),
    ]
