# Generated by Django 4.2 on 2023-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleitem",
            options={"verbose_name_plural": "9. Sales Item"},
        ),
        migrations.AddField(
            model_name="saleitem",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
