# Generated by Django 4.2 on 2023-04-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleinvoice",
            name="payment_entry",
        ),
        migrations.AddField(
            model_name="payment_entry",
            name="customer_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment_entry",
            name="sales_invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.saleinvoice",
            ),
            preserve_default=False,
        ),
    ]
