# Generated by Django 4.1.7 on 2023-10-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchaseitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(default='Test', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(default='Test', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
    ]
