# Generated by Django 4.2 on 2023-05-10 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_inventory_return_qty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment_entry",
            options={"verbose_name_plural": "8. پارەدان"},
        ),
        migrations.RemoveField(
            model_name="payment_entry",
            name="customer_name",
        ),
        migrations.AddField(
            model_name="payment_entry",
            name="q_type",
            field=models.CharField(
                choices=[
                    ("نقد", "نقد"),
                    ("قستی ١", "قستی ١"),
                    ("قستی ٢", "قستی ٢"),
                    ("قستی ٣ ", " قستی ٣"),
                    ("قستی ٤", "قستی ٤"),
                    ("قستی ٥", "قستی ٥"),
                    ("قستی ٦ ", " قستی ٦"),
                    ("قستی ٧", "قستی ٧"),
                    ("قستی ٨", "قستی ٨"),
                    ("قستی ٩ ", " قستی ٩"),
                    ("قستی ١٠", "قستی ١٠"),
                    ("قستی ١١", "قستی ١١"),
                    ("قستی ١٢ ", " قستی ١٢"),
                ],
                default=1,
                max_length=10,
                verbose_name="Payment type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleitem",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="discount_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sub_total",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="payment_entry",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="payment_entry",
            name="note",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment_entry",
            name="paid_amount",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="payment_entry",
            name="payment_date",
            field=models.DateTimeField(),
        ),
    ]
