# Generated by Django 4.2 on 2023-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_payment_entry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoice",
            name="note",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("مدفوع", "مدفوع"),
                    ("غير مدفوع", "غير مدفوع"),
                    ("المردود", "المردود"),
                ],
                default="مدفوع",
                max_length=10,
            ),
        ),
    ]
