# Generated by Django 4.2 on 2023-05-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_saleinvoice_note_alter_saleinvoice_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "الزبائن"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name_plural": " الموظفون"},
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": " تفاصيل المخزون"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name_plural": "المواد"},
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={"verbose_name_plural": " المصاريف"},
        ),
        migrations.AlterModelOptions(
            name="payment_entry",
            options={"verbose_name_plural": "إدخال الدفع"},
        ),
        migrations.AlterModelOptions(
            name="purchase",
            options={"verbose_name_plural": " فاتورة الشراء"},
        ),
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={"verbose_name_plural": " العنصر الذي تم شراؤه"},
        ),
        migrations.AlterModelOptions(
            name="salary",
            options={"verbose_name_plural": " الرواتب"},
        ),
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={"verbose_name_plural": "فاتورة البيع"},
        ),
        migrations.AlterModelOptions(
            name="saleitem",
            options={"verbose_name_plural": " بند المبيعات"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name_plural": "الوحدات"},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name_plural": " الموردين"},
        ),
        migrations.AlterField(
            model_name="saleinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("مدفوع", "مدفوع"),
                    ("غير مدفوع", "غير مدفوع"),
                    ("المردود", "المردود"),
                ],
                default="مدفوع",
                max_length=10,
            ),
        ),
    ]
