# Generated by Django 4.1.7 on 2023-10-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_entry',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment_entry',
            name='q_type',
            field=models.CharField(choices=[('نقد', 'نقد'), ('قسطی ١', 'قسطی ١'), ('قسطی ٢', 'قسطی ٢'), ('قسطی ٣ ', 'قسطی ٣'), ('قسطی ٤', 'قسطی ٤'), ('قسطی ٥', 'قسطی ٥'), ('قسطی ٦ ', 'قسطی ٦'), ('قسطی ٧', 'قسطی ٧'), ('قسطی ٨', 'قسطی ٨'), ('قسطی ٩ ', 'قسطی ٩'), ('قسطی ١٠', 'قسطی ١٠'), ('قسطی ١١', 'قسطی ١١'), ('قسطی ١٢ ', 'قسطی ١٢')], max_length=10, verbose_name='Payment type'),
        ),
    ]
