# Generated by Django 4.2 on 2023-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customer_options_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
