# Generated by Django 4.1.7 on 2023-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_payment_entry_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="open_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20
            ),
        ),
    ]
