# Generated by Django 4.1.7 on 2023-12-11 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_rename_note_customer_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="notes",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="open_balance",
        ),
        migrations.CreateModel(
            name="CustomerOpenBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
            ],
        ),
    ]
