# Generated by Django 4.1.7 on 2023-12-11 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_customer_open_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="open_balance",
        ),
    ]
