# Generated by Django 4.1.7 on 2023-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_customer_open_balance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerOpenBalance",
        ),
    ]
