# Generated by Django 4.1.7 on 2023-12-25 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_openingbalance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openingbalance",
            options={"verbose_name_plural": " رصيد افتتاحي"},
        ),
    ]
