# Generated by Django 4.1.7 on 2024-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_saleinvoice_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='modified_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
