# Generated by Django 4.1.7 on 2024-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_saleitem_modified_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='modified_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Modified Price'),
        ),
    ]
